package com.rajit.swadisht.adapter

import android.view.LayoutInflater
import android.view.ViewGroup
import androidx.recyclerview.widget.RecyclerView
import com.rajit.swadisht.data.model.OnboardingItem
import com.rajit.swadisht.databinding.OnboardingItemContainerBinding

/*
*   @OnboardingAdapter is an adapter of ViewPager2 used in MainActivity Layout
*   Used for Onboarding Screens to dynamically populate data into a reusable view
*   @param `onboardingItems` comes from AppConstants file under utils folder
*/
class OnboardingAdapter(private val onboardingItems: List<OnboardingItem>)
    :RecyclerView.Adapter<OnboardingAdapter.OnboardingViewHolder>(){

    /*
    *   @OnboardingViewHolder is a ViewHolder for the ViewPager
    *   Contains OnboardingItemContainer Layout for Onboarding Screens
    *   @param `binding` comes from auto-generated OnboardingItemContainerBinding class
    *   generated by ViewBinding
    */
    inner class OnboardingViewHolder(private val binding: OnboardingItemContainerBinding):
            RecyclerView.ViewHolder(binding.root) {
        fun bind(onboardingItem: OnboardingItem) {
            binding.apply{
                itemImage.setImageResource(onboardingItem.onboardingImage)
                itemTitle.text = onboardingItem.onboardingTitle
                itemDescription.text = onboardingItem.onboardingDescription
            }
        }
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): OnboardingViewHolder {
        val inflater = LayoutInflater.from(parent.context)
        val binding = OnboardingItemContainerBinding.inflate(inflater, parent, false)
        return OnboardingViewHolder(binding)
    }

    // Gets the list size from the supplied list of OnboardingItems
    override fun getItemCount(): Int {
        return onboardingItems.size
    }

    override fun onBindViewHolder(holder: OnboardingViewHolder, position: Int) {
        val currentItem = onboardingItems[position]
        holder.bind(currentItem)
    }

}